Fix Travis builds (?), (update deps?)
w3c/mobile-web-browser-emulator pull request #15
Opened 2017-04-29 20:09 UTC by qwertychouskie

Closes #13
May be needed for https://github.com/w3c/Mobile-Checker/pull/140

2017-04-29 22:38 UTC, qwertychouskie commented
Getting close, 6/7 tests passing...

2017-04-30 00:07 UTC, qwertychouskie commented
"Done. Your build exited with 0." Wooho! @dontcallmedom @tripu If one (or both) of you could make sure I didn't do anything wrong (especially in [browser-emulator-tests.js](https://github.com/w3c/mobile-web-browser-emulator/pull/15/files#diff-d094441bdfaa42119332480b2b541ed9), then merge the PR and push the update to NPM, that would be highly appreciated.

2017-04-30 00:43 UTC, qwertychouskie commented
P.S. Probably merge as one commit :)

2017-05-03 08:01 UTC, dontcallmedom commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
this is definitely wrong - this means `done` gets called as soon this code is read, when it is supposed to be fired when `browser.close()` finishes

2017-05-03 20:24 UTC, qwertychouskie commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
Should be fixed in latest commit.

2017-05-03 20:25 UTC, qwertychouskie commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
@dontcallmedom Should be fixed in latest commit.

2017-05-04 09:26 UTC, dontcallmedom commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
sorry, I think I was unclear - `then(done)` is what needs to be made to work - the two other usage of `done` you've suggested hide the problem rather than fix the bug.

To be more specific - if `done()` is called before `browser.close()` terminates (which happens both with `b.close().then(done())` and `b.close(); done();`) then we don't test that the `close()` method properly resolve its promise - and since it doesn't, there is a bug that needs fixing, not hiding :)

Thanks

2017-05-05 15:58 UTC, tripu commented
@qwertychouskie, may I suggest you add a `.gitignore` containing:

```
node_modules/
browsermob-proxy-2.1.4/
bmp.log
browsermob-proxy-2.0-beta-9
browsermob-proxy-2.1.4-bin.zip
```

?

2017-05-05 16:08 UTC, tripu commented on test/browser-emulator-tests.js
> +                'Failed gathering network traffic: Error: connect ECONNREFUSED 127.0.0.1:9999'
I had to change this IP address here to `127.0.1.1` (that's my `localhost`, don't ask me why :) to make this work. Apart from this, all tests run okay for me now.

Is there a way to make this more robust, and less dependant on the loopback?

2017-05-05 20:24 UTC, qwertychouskie commented on test/browser-emulator-tests.js
> +                'Failed gathering network traffic: Error: connect ECONNREFUSED 127.0.0.1:9999'
Fixed in https://github.com/w3c/mobile-web-browser-emulator/pull/15/commits/1a8956ce53c07aa1b7a41c97ae7acbce5f7f73f1

2017-05-05 20:50 UTC, qwertychouskie commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
`done` is a variable passed to the `it()` function (see lines 12-13), so the way it was, `done()` (the function that ends the test) was never called.  Maybe:
```
browser.close().then(done);
done();
```

2017-05-08 09:58 UTC, tripu commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
@qwertychouskie: the function `done` should be invoked when the promise returned by `close()` resolves; your change invokes it immediately. I think @dontcallmedom is right here.

2017-05-08 10:11 UTC, tripu commented on test/browser-emulator-tests.js
> +                'Failed gathering network traffic: Error: connect ECONNREFUSED 127.0.0.1:9999'
Ah, it was easy enough&nbsp;&mdash;&nbsp;I should have done it myself.
Thank you!

2017-05-08 10:12 UTC, tripu requested changes
There is a lot in `.gitignore` that we don't need. Can we keep it to the minimum, please?

2017-05-08 16:31 UTC, qwertychouskie commented
@tripu I used GitHub's template for node projects.

2017-05-08 16:34 UTC, qwertychouskie commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
How should it be done then?  The way it was done before never worked: https://travis-ci.org/w3c/mobile-web-browser-emulator/builds

2017-05-08 16:40 UTC, tripu commented
@qwertychouskie, templates are handy for quickly bootstrapping a project with a complex setup, I guess.
We know what we need; all those extra lines &ldquo;just in case&rdquo; are a bit noisy, IMHO.

2017-05-08 16:46 UTC, qwertychouskie commented
Just removed all unneeded lines in .gitignore.

2017-05-08 18:16 UTC, tripu approved these changes
There are still a few lines I don't see necessary for us, but I don't want to hold this PR.
@dontcallmedom?

2017-05-09 10:10 UTC, dontcallmedom commented on test/browser-emulator-tests.js
> +        browser.close().then(done());
I'm quite sure it used to work, although there may have been troubles reproducing that success on Travis (my memories are starting to be fuzzy).

In any case, I prefer a Travis build that fails for good reasons (here, the fact that the `browser.close` promise doesn't resolve correctly) rather than a Travis build that succeeds and hides bugs.

Can you revert that particular set of changes (back to `browser.close().then(done);`) so that we can merge the rest of excellent changes? Even if the Travis build still fails, it will be in a much better starting point

2017-05-09 10:12 UTC, dontcallmedom commented
I would prefer we not merge the changes to `browser.close.then(done)` but otherwise, I'm eager to see this merged :)

Many thanks @qwertychouskie

2017-05-11 20:45 UTC, qwertychouskie commented
Pushed another change, now uses:
```
browser.close().then(done);
done();
```

2017-05-16 15:23 UTC, tripu commented on test/browser-emulator-tests.js
>          done();
@qwertychouskie, I think these lines you added are still wrong&hellip;

```javascript
done();
```

2017-05-16 15:28 UTC, tripu requested changes
Please see last inline comment.

2017-05-17 01:00 UTC, qwertychouskie commented on test/browser-emulator-tests.js
>          done();
All `done()`s removed.

2017-05-17 06:30 UTC, tripu approved these changes

2017-05-17 06:31 UTC, tripu commented
Thank you, @qwertychouskie.
Back to @dontcallmedom.

2017-05-17 12:03 UTC, merged